name: Simple SonarQube Scan

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  name: SonarQube Integration
  sonarqube:
    name: SonarQube Integration
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone for better SonarQube analysis
        fetch-depth: 0

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
<<<<<<< HEAD
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
=======
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} //Sonar Token generated 
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} 
>>>>>>> 536cc77f7332f4e3277d8ebe5cb637485b1fe670
